Workers Docker images refactoring.

diff --git a/workers/dockerfiles/Dockerfile.affymetrix_local b/workers/dockerfiles/Dockerfile.affymetrix_local
--- a/workers/dockerfiles/Dockerfile.affymetrix_local
+++ b/workers/dockerfiles/Dockerfile.affymetrix_local
@@ -1,14 +1,18 @@
 FROM ccdlstaging/dr_affymetrix:latest
 
-USER root
+# Fail in case of an error at any stage in the pipe.
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+
+WORKDIR /home/user
 
 # Remove the version of common already installed.
-RUN rm -r common/
-RUN pip3 uninstall -y data_refinery_common
+RUN rm -r common && \
+    pip3 uninstall -y data_refinery_common
 
 # Get the latest version from the dist directory.
 COPY common/dist/data-refinery-common-* common/
-RUN pip3 install common/$(ls common -1 | sort --version-sort | tail -1)
+RUN pip3 install --ignore-installed --no-cache-dir \
+    common/$(ls common -1 | sort --version-sort | tail -1)
 
 ARG SYSTEM_VERSION
 
diff --git a/workers/dockerfiles/Dockerfile.transcriptome b/workers/dockerfiles/Dockerfile.transcriptome
--- a/workers/dockerfiles/Dockerfile.transcriptome
+++ b/workers/dockerfiles/Dockerfile.transcriptome
@@ -1,87 +1,41 @@
-FROM ubuntu:18.04
+FROM ccdlstaging/dr_worker_base:latest
 
-# Prevent tzdata from prompting us for a timezone and hanging the build.
-ENV DEBIAN_FRONTEND=noninteractive
+# Fail in case of an error at any stage in the pipe.
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
-# Source: https://github.com/thisbejim/Pyrebase/issues/87#issuecomment-354452082
-# For whatever reason this worked and 'en_US.UTF-8' did not.
-ENV LANG C.UTF-8
-
-RUN apt-get update -qq
-RUN apt-get install -y software-properties-common
-RUN add-apt-repository ppa:apt-fast/stable
-RUN add-apt-repository ppa:deadsnakes/ppa
-RUN add-apt-repository ppa:savoury1/llvm-defaults-10
-
-RUN apt-get update -qq
-RUN apt-get -y install apt-fast
-
-RUN apt-fast update -qq && apt-fast install -y \
-  build-essential \
-  curl \
-  cython3 \
-  ed \
-  git \
-  libcurl4-openssl-dev \
-  libfreetype6-dev \
-  libpq-dev \
-  llvm-10-dev \
-  pkg-config \
-  python3-pip \
-  python3.8 \
-  python3.8-dev \
-  wget \
-  zlib1g-dev
-
-RUN rm CRAN.gpg
-RUN apt-get clean; rm -rf /var/lib/apt/lists/*
-RUN ln -s /usr/bin/llvm-config-10 /usr/bin/llvm-config
-RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
-
-RUN groupadd user && useradd --create-home --home-dir /home/user -g user user
 WORKDIR /home/user
 
 # It's annoying that this can only be installed via git.
-RUN git clone https://github.com/deweylab/RSEM.git
-RUN cd RSEM && make install
-RUN rm -rf RSEM
+RUN git clone https://github.com/deweylab/RSEM.git && \
+    cd RSEM && make install && \
+    rm -rf RSEM
 
-# Install Salmon
-
-# Tximport requires all experiments to be processed with the same version of Salmon to work https://github.com/AlexsLemonade/refinebio/issues/1496
+# Install Salmon.
+# Tximport requires all experiments to be processed with the same version of
+# Salmon to work https://github.com/AlexsLemonade/refinebio/issues/1496.
 # This is something that should be considered when updating salmon, because
 # all samples from incomplete experiments must have salmon run on them again.
 ENV SALMON_VERSION 0.13.1
 
-# Doesn't work:
-# salmon: relocation error: /usr/local/bin/../lib/librt.so.1: symbol __vdso_clock_gettime, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
-# ENV SALMON_VERSION 0.10.0
-
-# Binary releases moved to bioconda, doesn't work anymore.
-# ENV SALMON_VERSION 0.10.2
-
-RUN wget https://github.com/COMBINE-lab/salmon/releases/download/v${SALMON_VERSION}/Salmon-${SALMON_VERSION}_linux_x86_64.tar.gz
-RUN tar -xzf Salmon-${SALMON_VERSION}_linux_x86_64.tar.gz
-
 # Salmon can extract to a different directory than the name of the tar file.
-RUN cp `tar -tzf Salmon-${SALMON_VERSION}_linux_x86_64.tar.gz | head -1 | cut -f1 -d"/"`/bin/salmon /usr/local/bin
-RUN cp `tar -tzf Salmon-${SALMON_VERSION}_linux_x86_64.tar.gz | head -1 | cut -f1 -d"/"`/lib/* /usr/local/lib
-
-RUN rm -r Salmon*
+RUN wget -q "https://github.com/COMBINE-lab/salmon/releases/download/v${SALMON_VERSION}/Salmon-${SALMON_VERSION}_linux_x86_64.tar.gz" && \
+    tar -xzf "Salmon-${SALMON_VERSION}_linux_x86_64.tar.gz" && \
+    cp "$(tar -tzf Salmon-${SALMON_VERSION}_linux_x86_64.tar.gz | \
+        head -1 | cut -f1 -d '/')/bin/salmon" /usr/local/bin && \
+    cp "$(tar -tzf Salmon-${SALMON_VERSION}_linux_x86_64.tar.gz | \
+        head -1 | cut -f1 -d '/')/lib/"* /usr/local/lib/ && \
+    rm -r Salmon*
 # End Salmon installation.
 
-RUN pip3 install --upgrade pip
-RUN pip3 install numpy
+RUN pip3 install --ignore-installed --no-cache-dir --upgrade pip && \
+    pip3 install --ignore-installed --no-cache-dir numpy
+
+COPY common/dist/data-refinery-common-* common/
+RUN pip3 install --ignore-installed --no-cache-dir \
+    common/$(ls common -1 | sort --version-sort | tail -1)
 
 COPY workers/data_refinery_workers/processors/requirements.txt .
-RUN pip3 install --ignore-installed -r requirements.txt
-
-# Get the latest version from the dist directory.
-COPY common/dist/data-refinery-common-* common/
-RUN pip3 install common/$(ls common -1 | sort --version-sort | tail -1)
-
-# Clear out the pip3 cache.
-RUN rm -rf /root/.cache
+RUN pip3 install --ignore-installed --no-cache-dir -r requirements.txt
 
 ARG SYSTEM_VERSION
 
